### ISSUE TITLE
Fullstack-harjoitustyön katselmointi

### ISSUE THREAD

**Issue by ShootingStar91** [jpronkko/texter#14]
# Fullstack-harjoitustyön katselmointi

Tämä on katselmointi harjoitustyöstäsi. Sinun ei tarvitse toteuttaa mahdollisia parannusehdotuksia saadaksesi suorituksen.

### Käyttökokemus

+ Selkeä ja hyvä UI
+ Rekisteröityminen toteutettu hyvin: notifikaatiot ja validaatiovirheet hyvin näkyvillä
+ Ehkä ainoa hienosäätö olisi laittaa jokin latausikoni lomakkeen syötön jälkeen, jotta käyttäjä tietää heti että painallus meni läpi ja jotain tapahtuu
+ Eri näkymiä ladattaessa näkyy latausanimaatio joka saa selaamisen tuntumaan sulavalta
+ Kokeilin kaikenlaista mitä löysin sovelluksesta: 
  + Loin ryhmiä ja niihin kanavia
  + Kutsuin toisen käyttäjän ja säädin tämän oikeuksia
  + Postin kanavan
  + Kaikki tuntuu toimivan hyvin, ja esimerkiksi oikeuksien säätö tai kutsun hyväksyminen tapahtuu välittömästi siten että adminin ei tarvitse ladata sivua uudelleen vaan muutos tulee välittömästi näkyviin.
+ Kaikenkaikkiaan selkeä ja helppo käyttää, ja ominaisuuksia löytyy hyvin.

### Koodi

+ Koodi on selkeää, formatoitua, ja hyvin jäsennelty eri tiedostoihin ja kansioihin
+ Kirjastoja ja teknologioita kuten react-hook-form, MaterialUI, yup, redux ja GraphQL on käytetty fiksusti
+ Koodista ei valittamista, sekä palvelimella että frontissa näyttää hyvältä ja saatu paljon aikaan järkevällä määrällä koodia.
+ Testejäkin löytyy

### Yhteenveto

Sovellus on siisti ja toimiva kokonaisuus. Käyttö on helppoa ja ominaisuuksia löytyy hyvin. Projektin laajuus on onnistunut hyvin: Siinä on paljon ominaisuuksia mutta kaikki on tehty huolella, bugeja ei ole ja koodikin on laadukasta ja selkeää. Sovelluksen käytössä huomaa kaiken huolitellun hyvin, esimerkiksi latauspalkki näkymiä ladattaessa, ja GraphQL-subskriptiot hoitamaan tiedon päivittyminen ilman sivulatausta. Erittäin hyvää työtä! 💎

**Comment by jpronkko** [comment]
Kiitos positiivisesta palautteesta. React-hook-formin useForm näyttää palauttavan fieldStatessa isSubmitting muutujan. Kokeilen tuon avulla palautteen antamista käyttäjälle sisäänkirjautumislomakkeen ja uuden käyttäjän luontilomakkeen yhteydessä.
